### PR TITLE
Use Github stars, not downloads, for sorting metric.

### PR DESCRIPTION
**Pull request by markrickert**
This requires you to set up a personal token and place the token in the `.oauth_token` file for use by the github api gem.

I think this is a much better metric to sort by since gem download counts for old and frequently released gems will be higher than newer and arguably more stable gems.

### CODE REVIEW

**Comment by markrickert** [comment]
cc/ @twerth 
You're welcome :)

**Comment by clayallsopp** [comment]
awesome

**Comment by clayallsopp** [comment]
@markrickert @twerth this is now deployed: http://motion-toolbox.com/

**Comment by twerth** [comment]
Thanks Clay, now ProMotion is up where it deserves to be.

**Comment by markrickert** [comment]
Thanks Clay! Now we need to figure out how to get the to lay out in columns left to right instead of top to bottom. But my web skills have been slack recently.

**Pull request merged**
