### PR TITLE
Sorts gems by number of downloads.

### PR DESCRIPTION
**Pull request by markrickert**
Also outputs total downloads of gem to the website.

Comes with a nifty progress indicator for the rake task too!

### CODE REVIEW

**Comment by clayallsopp** [comment]
Ha, very cool! Let me give it a shot

**Comment by clayallsopp** [comment]
@markrickert I gave it a go locally, pretty sweet feature

can we format the download number somehow? like `100k downloads` instead of `144,194`

and can we also move it out of the `gem install` label? it looks a bit weird when the line breaks. maybe put it its own bubble-label, which is forced onto a new line?

**Comment by markrickert** [comment]
I've update my branch with abbreviations on the numbers. 

Here's what it looks like: 

screenshot 2015-02-27 09 28 21

**Comment by clayallsopp** [comment]
@markrickert merged and deployed!

i made one small change - by default, it will always fetch the gems when you start middleman (this can be skipped by setting a `SKIP_GEMS` environment variable)

**Comment by markrickert** [comment]
Nice! Thanks for merging! It's a pain to grab all the data from rubygems since you have to make a separate call for each gem. I wish there was a way to send a list of gem names to the api and get just one property of the gem.

I think i see a PR on the rubygems API repo in my future! lol

**Pull request merged**
